version: '3.11'
services:
  app:
    build: ./app
    restart: always
    volumes:
      - ./app:/app
    depends_on:
      - iris
    links:
      - iris
    ports:
      - 8011:8011

  iris:
    build:
      context: ./iris
      dockerfile: Dockerfile
    restart: always
    hostname: iris
    command: --password-file password.txt --check-caps false
    ports:
      - 1972:1972
      - 52773:52773
      - 53773:53773
    expose:
      - "51773"